#! /usr/bin/perl
# tex/labels/makelabel.pl   2017-9-29   Alan U. Kennington.
# $Id: tex/labels/makelabel.pl 53beb71aa5 2017-09-29 11:52:53Z Alan U. Kennington $

# This is a Perl script for making a label.
# Usage: ./makelabel.pl <filename.txt>

my $deft_n_columns = 22;

my $n_args = $#ARGV + 1;
if ($n_args != 1) {
    print STDERR "Usage:   $0 <filename.txt>\n";
    print STDERR "Example: $0 label1.txt\n";
    exit(1);
    }

# The file to be filtered.
my $f = $ARGV[0];
print "Reading file \"$f\"\n";
if (! -e $f) {
    print STDERR "Error: file \"$f\" does not exist\n";
    print STDERR "Usage: $0 <filename.txt>\n";
    exit(1);
    }
if (! -f $f) {
    print STDERR "Error: file \"$f\" is not a plain file\n";
    print STDERR "Usage: $0 <filename.txt>\n";
    exit(1);
    }
if (-z $f) {
    print STDERR "Error: file \"$f\" is an empty file\n";
    print STDERR "Usage: $0 <filename.txt>\n";
    exit(1);
    }

# Check that the filename tail is ".txt".
my @names = split /\./, $f;
my $n_names = $#names;
my $t = $names[$n_names];
# print "t = \"$t\"\n";
if (lc($t) ne "txt") {
    print STDERR "Error: file \"$f\" is not a .txt file\n";
    print STDERR "Usage: $0 <filename.txt>\n";
    exit(1);
    }

# Determine the filename head.
my $head = $f;
$head =~ s/(.*)\.[^\.]+/$1/;
# print "head = \"$head\"\n";

#------------------------------------------------------------------------------
# Read the file.
open(my $fhand, '<', $f)
    or die "Error: Could not open file \"$f\" for reading\n";

my $n_lines = 0;
my $n_columns = 0;
my @lines_txt;
while (my $line = readline($fhand)) {
    chomp($line);
    $n_lines += 1;
    $n_columns += 1;
    $lines_txt[$n_columns] = $line;
#    print "line = \"$line\"\n";
    }

print "Found $n_lines lines in file \"$f\".\n";
my $n_columns_blank = 0;
my $n_columns_ignore = 0;
if ($n_columns < $deft_n_columns) {
    $n_columns_blank = $deft_n_columns - $n_columns;
    print "Will print $n_columns_blank blank lines on the right.\n";
    }
if ($n_columns > $deft_n_columns) {
    $n_columns_ignore = $n_columns - $deft_n_columns;
    print "Will ignore the last $n_columns_ignore lines.\n";
    }

#==============================================================================
# Name of MetaPost output file.
my $f_mp = "$head.mp";

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
my $text_mp_top =
"% $f_mp
% MetaPost file \"$f_mp\" generated by \"makelabel.pl\" from \"$f\".

% prologues := 1;

beginfig(1);
boolean draw_arrow;
pair zz[];
color col[];
string label[];

col1 := white;              % The light colour.
col2 := 0.70white;          % The dark colour.

% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
% All of the labels from 1 to 22 must be defined once and only once.
% Blank labels should be given as the empty string, which is \"\".
";

#------------------------------------------------------------------------------
my $text_mp_mid = "";
for (my $i = 1; $i <= $deft_n_columns; $i += 1) {
    # NOTE: Should escape '"' as '\"' here to prevent MetaPost bugs.
    if (defined($lines_txt[$i])) {
        if ($lines_txt[$i] !~ m/<<</) {
            $text_mp_mid .= "label[$i] := \"$lines_txt[$i]\";\n";
            $text_mp_mid .= "label[100 + $i] := \"\";\n";
            $text_mp_mid .= "label[200 + $i] := \"\";\n";
            }
        else {
            my ($text_l, $text_r) = split(/ *<<< */, $lines_txt[$i], 2);
            $text_mp_mid .= "label[$i] := \"\";\n";
            $text_mp_mid .= "label[100 + $i] := \"$text_l\";\n";
            $text_mp_mid .= "label[200 + $i] := \"$text_r\";\n";
            }
        }
    else {
        $text_mp_mid .= "label[$i] := \"\";\n";
        $text_mp_mid .= "label[100 + $i] := \"\";\n";
        $text_mp_mid .= "label[200 + $i] := \"\";\n";
        }
    }

#------------------------------------------------------------------------------
my $text_mp_bot =
"% Number of labels. Must always be 22.
n_labels := 22;

% The choice of font.
defaultfont := \"phvr8r\";
% defaultfont := \"cmr9\";

% Dot and line widths.
penARROW := 0.5bp;
penDOT := 2.5bp;
penBDY := 0.5bp;
penBOX := 0.5bp;

% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
% Width of all 22 columns, ignoring the extension on the right.
wsquares := 19.4 cm;

% Width of one square.
wsquare := wsquares / n_labels;

% X and Y coordinates of the sloping lines.
Xslope := 3.1cm;
Yslope := 3.4cm;

% The angle (in degrees anticlockwise) to tilt the text.
% Not really 45 degrees. Need arctan(y/x).
% angle_label := 45;
zz20 := (Xslope, Yslope);
zz21 := zz20 rotated -90;
angle_label := angle(zz20);

draw_arrow := false;

% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
d1 := 12pt;
d1h := d1 * sqrt(2);
h1 := 1mm;                  % Arrow distance from text.
len1 := 4mm;                % Arrow length.
h2 := h1 + len1;
dx1 := 0.1mm;               % Offset of text from arrows.
gap1 := 1mm;
zz0 := (50, 50);
dsplit := 6bp;              % Offsets for a double-row column.

% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
for i=1 upto n_labels:
    % Add the colour.
    zz30 := zz0 + (0, -wsquare * (i - 1));
    zz31 := zz0 + (0, -wsquare * i);
    zz32 := zz31 + zz21;
    zz33 := zz30 + zz21;
    if (i mod 2) = 1:
        col3 := col1;
    else:
        col3 := col2;
        fi
    pickup pencircle scaled penBOX;
    fill zz30--zz31--zz32--zz33--cycle withcolor col3;
    draw zz30--zz31--zz32--zz33--cycle;
    % Do the text.
    zz1 := zz0 + (0, -wsquare * (i - 0.5));
    if label[i] <> \"\":
        draw thelabel.rt(label[i] infont defaultfont, (0,0))
            rotated (angle_label - 90) shifted (zz1+(0, dx1));
    elseif label[100 + i] <> \"\":
        draw thelabel.rt(label[100 + i] infont defaultfont, (0,0))
            rotated (angle_label - 90) shifted (zz1+(0, dx1+dsplit));
        draw thelabel.rt(label[200 + i] infont defaultfont, (0,0))
            rotated (angle_label - 90) shifted (zz1+(0, dx1-dsplit));
        fi
    if (label[i] <> \"\") and draw_arrow:
        zz2 := zz1 + (-h1, 0);
        zz3 := zz1 + (-h2, 0);
%        pickup pencircle scaled penDOT;
%        draw zz2;
        pickup pencircle scaled penARROW;
        drawarrow zz2--zz3;
        fi
    endfor

% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
% Draw a bounding box.
if draw_arrow:
    zz10 := zz0 + (-h2 - gap1, 0);
else:
    zz10 := zz0;
    fi
zz11 := zz10 + (0, -wsquares);
zz12 := zz11 + zz21;
zz13 := zz10 + zz21;

pickup pencircle scaled penBDY;
draw zz10--zz11--zz12--zz13--cycle;

endfig;
end
";

#------------------------------------------------------------------------------
# Write MetaPost text to mp file.
# print "MetaPost top-text:\n$text_mp_top";
# print "MetaPost mid-text:\n$text_mp_mid";
# print "MetaPost bottom-text:\n$text_mp_bot";

#------------------------------------------------------------------------------
print "Writing MetaPost file \"$f_mp\"...\n";
open($fhand_mp, '>', $f_mp)
    or die "Error: Could not open file \"$f_mp\" for writing\n";

print $fhand_mp $text_mp_top, $text_mp_mid, $text_mp_bot;
# print $fhand_mp $text_mp_mid;

#==============================================================================
# Name of TeX output file.
my $f_tex = "$head.tex";
my $f_1 = "$head.1";

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
my $text_tex =
"% $f_tex
% Labels generated from file \"$f\".

\\input epsf

\\nopagenumbers
\\parindent0pt
\\def\\lgap{\\hskip10pt\\relax}

% Adjust the printing area for A4 paper.
\\hoffset=-2.838mm
\\vsize=29.73017788cm
\\advance\\vsize by-2.54cm            % Top margin
\\advance\\vsize by-2.54cm            % Bottom margin
\\advance\\vsize by-0.9cm             % Allowance for page number in footer.

\\centerline{\\epsfbox{$f_1}\\lgap%
\\epsfbox{$f_1}\\lgap%
\\epsfbox{$f_1}\\lgap%
\\epsfbox{$f_1}\\lgap%
\\epsfbox{$f_1}}

\\bye
";

#------------------------------------------------------------------------------
print "Writing TeX file \"$f_tex\"...\n";
open($fhand_tex, '>', $f_tex)
    or die "Error: Could not open file \"$f_tex\" for writing\n";

print $fhand_tex $text_tex;

__END__
